# Generated by Django 3.1.5 on 2021-01-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('subtitle_1', models.CharField(max_length=50)),
                ('para_1', models.TextField()),
                ('subtitle_2', models.CharField(blank=True, max_length=50)),
                ('para_2', models.TextField(blank=True)),
                ('description', models.CharField(default='none', max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('creator', models.CharField(max_length=30)),
            ],
        ),
    ]
