# Generated by Django 3.1.5 on 2021-01-10 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20210110_0941'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comments',
        ),
    ]
