# Generated by Django 3.1.5 on 2021-01-05 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login_form', '0004_auto_20210105_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='password',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
