# Generated by Django 3.1.5 on 2021-01-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_form', '0005_auto_20210105_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='password',
            field=models.CharField(max_length=40),
        ),
    ]
