# Generated by Django 3.1.5 on 2021-01-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_form', '0006_auto_20210105_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='form',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
