# Generated by Django 3.1.5 on 2021-01-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_form', '0007_auto_20210108_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='terms_condition',
            field=models.BooleanField(blank=True, default=True, verbose_name='I agree to terms and conditions'),
        ),
    ]
